driver:
 name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
- name: centos-6.7
- name: centos-7.1

suites:
  - name: default
    run_list:
       - recipe[test_tuned::create_apply_profile]
    attributes:
  - name: provider
    run_list:
       - recipe[test_tuned::create_provider_apply_profile]
    attributes:
  - name: manage
    run_list:
      - recipe[tuned::manage]
    attributes:
      tuned:
        enabled_profile: latency-performance
  - name: manage-custom
    run_list:
      - recipe[tuned::manage]
    attributes:
      tuned:
        profile:
          myprofile:
            vm:
              transparent_hugepage: never
              transparent_hugepage.defrag: never
            main:
              include: latency-performance
        enabled_profile: myprofile